/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/common/add.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    List: typeof import('./src/components/account/list.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    PageScroll: typeof import('./src/components/common/pageScroll.vue')['default']
    PieChart: typeof import('./src/components/account/pieChart.vue')['default']
    Statistics: typeof import('./src/components/account/statistics.vue')['default']
  }
}
